pkg_name=user-linux-api-profiles
pkg_version=0.1.0
pkg_origin=chef
pkg_scaffolding="ci/scaffolding-chef-inspec"
scaffold_inspec_client="chef/inspec/4.18.51"
scaffold_profiles=(
  profile1
  profile2
)
