pkg_name=linux-policyfile-cookbook
pkg_origin=example-corporation
pkg_version="0.1.0"
pkg_maintainer="Chef"
pkg_license=("Apache-2.0")
pkg_scaffolding="chef/scaffolding-chef-infra"
scaffold_policy_name="Policyfile"
scaffold_policyfile_path="$PLAN_CONTEXT/../" # habitat/../Policyfile.rb
scaffold_chef_license="accept-no-persist"
