$pkg_name="effortless-config-baseline"
$pkg_origin="chef"
$pkg_version="0.1.0"
$pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
$pkg_license=("Apache-2.0")
$pkg_description="A Chef Example of the Effortless Config Pattern"
$pkg_upstream_url="http://chef.io"
$pkg_scaffolding="chef/scaffolding-chef-infra"
$scaffold_policy_name="base"
